name: Build Vue
on: 
  push:
    branches: [v_1_1]
jobs:
  build_vue:
    runs-on: self-hosted
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'Kirill-Kyrgansky'
        reponame: 'cheesemaker-server-serve'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
